### ISSUE TITLE
bug:Nothing with this path exists or you do not have access to it!

### ISSUE THREAD

**Issue by ToonPatrol** [swmff/rainbeam#25]
**Describe the bug**
"Nothing with this path exists or you do not have access to it!" I get this error message anytime I try to ask a question.

**To Reproduce**
Ask a question

**Expected behavior**

**Screenshots**

**Specifications**
Brave and Firefox

**Additional context**

**Comment by trisuaso** [comment]
I've never been able to reproduce this bug, but I've slightly updated the way questions are asked, so this may be fixed for you now. We previously pulled the user from username while asking questions, but will now accept either username or ID.

Feel free to reopen this if the issue still persists after Rainbeam v1.8.1.
