### ISSUE TITLE
feature:help translation?

### ISSUE THREAD

**Issue by alternative00** [swmff/rainbeam#30]
Can I help Korean Translation for NeoSpring?

**Comment by trisuaso** [comment]
Absolutely!

I need to actually prepare a lot of the code to allow different languages, so that will probably take some time.

I will let you know when everything is setup and then I will tell you how to contribute translations.

Thanks!

**Comment by trisuaso** [comment]
A translation can now be contributed by copying the file at `langs/en-US.json` to `langs/ko-KR.json` and editing it to provide translations.

Only the `value` should be updated!

```json
{
    "data": {
        "key": "value",
    }
}
```

**Comment by alternative00** [comment]
thanks!

**Comment by alternative00** [comment]
https://github.com/alternative00/neosrping-ko/blob/main/ko-KR

You can use this file! thanks!

**Comment by trisuaso** [comment]
Perfect, thank you!

Feel free to reopen the issue if you ever need me to sync the file again.
