### ISSUE TITLE
It won't let me log in

### ISSUE THREAD

**Issue by Asheton-The-Trans-Boy** [swmff/rainbeam#31]
I don't know why but whenever I try to sign it it tells me that I'm not allowed to and I js wanna know if I got reported or if there's a bug or something like that

**Comment by Asheton-The-Trans-Boy** [comment]
This is for Neospring btw

**Comment by trisuaso** [comment]
This is the generic error for either incorrect password or incorrect username.

Try a different password (or make sure you typed right). You can email support@swmff.org if you're still unable to get it

**Comment by Asheton-The-Trans-Boy** [comment]
Yes thank u I got logged in
