### ISSUE TITLE
bug:Can’t log in

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/rainbeam#32]
I sent an email already but I need reassurance that this will be seen and taken care of;

I can’t log into either of my accounts, @rotten and @surgeon. I am still logged into both on separate devices, but on my laptop it won’t let me log in after I logged out. And I know I am putting in the correct password.

I sent more details including what I know my password should be through email, please help!

**Comment by trisuaso** [comment]
What is the error message shown when trying to log in?
* If it's a "not allowed" message, then it's an invalid password
* If it's "you're banned" then you're IP banned from Neospring

**Comment by fleshorchestra** [comment]
It says “You are not allowed to access this resource. (NotAllowed)”

So, if I’m putting in my password wrong, despite the fact I know it’s
correct, is there some way I can have my password reset? Do I need to give
proof of ownership?

**Comment by trisuaso** [comment]
Yes, I can reset your password for you if you provide proof of ownership.

You can do so through email (**don't** do it here), or you can mail system (0) on Neospring:

https://neospring.org/inbox/mail/compose?to=0

**Comment by fleshorchestra** [comment]
Before I send an email, can you confirm you received my previous one? It
should be titled “Can’t Log in”. I just want to make sure that I don’t have
to go through my apple email (which clicking the support email link sends
me to), because it doesn’t send my emails. I use gmail. I emailed “
***@***.***” through my gmail.

**Comment by fleshorchestra** [comment]
I mailed through Neospring mail system on @surgeon.

**Comment by trisuaso** [comment]
New passwords sent through mail. Please change them as soon as you're able to log in.

Yes, I received the emails.

Going to close this since it seems resolved (I tested the login with the new passwords), but feel free to reopen if something goes wrong again.
