### ISSUE TITLE
bug: "An unspecified error has occured" "You are not allowed to access this resource. (NotAllowed)" 

### ISSUE THREAD

**Issue by BluOcean00** [swmff/rainbeam#33]
Whenever I'm trying to create an account it throws the messages stated on the title. I've tried with different usernames, passwords, tried redoing the captcha, tried from my computer and my phone, internet, no internet, nothing seems to work

1) Go to Sign Up
2) Complete the process down to the captcha and click sign up
3) The "An unspecified error has occured" should pop out, if you click once more the sign up button the "you are not allowed to access this resource" text should pop out afterwards

I expected to be greeted with either the homepage with public asks or my new profile

![image](https://github.com/user-attachments/assets/3cc08c97-fa9f-42d0-a03e-26e44451e873)

Firefox, duckduck go search engine, on both mobile and laptop

**Comment by trisuaso** [comment]
Fixed in 2b5503a

**Comment by dae500** [comment]
hello sorry to bother you 
I am unable to access my account and receive the error message: "You are not allowed to access this resource. (NotAllowed)." Could you please assist me in resolving this issue? thank you
