### ISSUE TITLE
bug: Drawing disappears upon fully loading profile

### ISSUE THREAD

**Issue by Robinik** [swmff/rainbeam#34]
**Describe the bug**
Whenever I visit a profile that features an ask with a drawing attached, the drawing appears for about a split second before disappearing permanently.

**To Reproduce**
1. Go to my profile. (@Grimmgall)
2. Wait for the page to fully load.
3. Scroll down to the currently only post on the page.
4. See the drawing completely blank after about a split second of viewing it.

**Expected behavior**
The drawing should appear permanently.

**Screenshots**

https://github.com/user-attachments/assets/d208b940-77d5-40f3-9140-31a397281b20

(This shows the #doodle tag, but it also appears on my profile in general. I wasn't able to capture it properly because it disappeared too quickly to properly capture it when I attempted it without the #doodle tag on my general profile page.)

**Specifications**
Windows 11 HP Laptop
Desktop mode
Google Chrome

**Additional context**
N/A?

**Comment by Robinik** [comment]
Edited to update the version of the video without my tabs or bookmarks showing. It's nobody's business what I browse. (It's nothing illegal or generally considered immoral, but a little embarrassing, especially a few without proper context.)

**Comment by trisuaso** [comment]
Fixed in 80999bc, feel free to reopen if it's still occurring

**Comment by trisuaso** [comment]
I manually deleted the first version of this issue because it included a link to the video containing your tabs. It is no longer accessible, but note GitHub stores edit history for every issue and comment!
