### ISSUE TITLE
bug:System mail feature not working

### ISSUE THREAD

**Issue by fleshorchestra** [swmff/rainbeam#35]
When I try to issue a report through the mail system (Mailing “0”) it gives me an error that says “An unspecified error has occurred”.
![IMG_4769](https://github.com/user-attachments/assets/28e1831c-e2b8-4d66-8d72-83ef506a089a)

The regular report system works just fine, I filed two reports for messages I received, but there is a bigger picture to an ongoing situation which is related to the harassment I received which I need to report, and would like to have a response.

**Comment by trisuaso** [comment]
It appears to be working, try again and let me know if it's still broken!

**Comment by fleshorchestra** [comment]
I tried again just now and it is still not working
![IMG_4967](https://github.com/user-attachments/assets/260ffec2-9964-4dd7-919e-dd71fbfdd602)

**Comment by trisuaso** [comment]
The support email has been received. We're reviewing it and will get back to you ASAP.

System mailing will be fixed soon!

**Comment by fleshorchestra** [comment]
Thank you so much!

**Comment by fleshorchestra** [comment]
Hi, I beg, please check the email again when possible. I added another report onto the thread which includes my friend’s face being posted on the service without their consent. This is doxxing. Please help. I sent the email, this is very important.

**Comment by trisuaso** [comment]
This feature is confirmed working.
