### ISSUE TITLE
poor installation steps

### ISSUE THREAD

**Issue by jakesullyneytiri** [swmff/rainbeam#39]
This isn't really a bug with script.

It's just that steps that shows:

git clone https://github.com/swmff/rainbeam
cd rainbeam
just build sqlite

makes no sense? it does not state an OS requirements, neither any packages that needs to be installed to get command just working etc.

So runing 2 cmds above and then just build sqlite gives me command just not found or -bash: just: command not found.

Could you guys be more clear and make proper step by step guide instead?

Update: You guys need to add following command

npm install -g just-install that way just command works.

Next problem after i got just command working i get this when writing just build sqlite or mysql or mariadb:

just build-assets
node ./crates/builder/index.js
node:internal/errors:478
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'lightningcss' imported from /home2/user/public_html/rainbeam/crates/builder/lib.js
    at new NodeError (node:internal/errors:387:5)
    at packageResolve (node:internal/modules/esm/resolve:852:9)
    at moduleResolve (node:internal/modules/esm/resolve:901:20)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
error: Recipe `build-assets` failed on line 16 with exit code 1
error: Recipe `build` failed on line 5 with exit code 1

Update 2: if i install missing packages manually, then i re-run just build mariadb again but this time i get following error

file:///home2/username/public_html/rainbeam/crates/builder/lib.js:285
            const text = await (
                         ^

ReferenceError: fetch is not defined
    at build (file:///home2/username/public_html/rainbeam/crates/builder/lib.js:285:26)
    at async file:///home2/username/public_html/rainbeam/crates/builder/index.js:8:5
error: Recipe `build-assets` failed on line 16 with exit code 1
error: Recipe `build` failed on line 5 with exit code 1

**Comment by trisuaso** [comment]
Absolutely correct, I'll update these ASAP.

A lot of the build system has changed since those were written, so this makes sense. I'll comment on this again when they have been updated so you can review them.

**Comment by trisuaso** [comment]
The installation steps have been updated in e7efe5486383a4493bb643c3cd763108b2c10d95, let me know if these work better for you.

**Comment by jakesullyneytiri** [comment]
> The installation steps have been updated in [e7efe54](https://github.com/swmff/rainbeam/commit/e7efe5486383a4493bb643c3cd763108b2c10d95), let me know if these work better for you.

thank you for updating the guide,

after doing just init-builder and then i ran just build mysql

but i still getting this:

file:///home2/username/public_html/rainbeam/crates/builder/lib.js:285
            const text = await (
                         ^

ReferenceError: fetch is not defined
    at build (file:///home2/username/public_html/rainbeam/crates/builder/lib.js:285:26)
    at async file:///home2/username/public_html/rainbeam/crates/builder/index.js:8:5
error: Recipe `build-assets` failed on line 16 with exit code 1
error: Recipe `build` failed on line 5 with exit code 1

**Comment by trisuaso** [comment]
What version of Node.js are you running? You may need to upgrade to a more recent version which supports the `fetch` API.

Confirmed working on Node v20.18.1.

**Comment by jakesullyneytiri** [comment]
> What version of Node.js are you running? You may need to upgrade to a more recent version which supports the `fetch` API.
> 
> Confirmed working on Node v20.18.1.

that did the trick, but when i tried to do cargo install just i keep getting this:

error: failed to run custom build command for `serde_json v1.0.134`

Caused by:
  could not execute process `/tmp/cargo-installETuHQr/release/build/serde_json-3d48d737f1de9025/build-script-build` (never executed)

Caused by:
  Permission denied (os error 13)
warning: build failed, waiting for other jobs to finish...
error: failed to run custom build command for `rayon-core v1.12.1`

Caused by:
  could not execute process `/tmp/cargo-installETuHQr/release/build/rayon-core-1b35d7c2324a40a3/build-script-build` (never executed)

Caused by:
  Permission denied (os error 13)
error: failed to compile `just v1.38.0`, intermediate artifacts can be found at `/tmp/cargo-installETuHQr`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

i have no idea how to fix this and googling it does not give proper answer.

**Comment by trisuaso** [comment]
Oh yeah, there's no run command missing because the location of the binary does not really matter, so it could be anywhere. I'll add that to the README.

A standard release build should place it at `./target/release/rainbeam`

**Comment by jakesullyneytiri** [comment]
> Oh yeah, there's no run command missing because the location of the binary does not really matter, so it could be anywhere. I'll add that to the README.
> 
> A standard release build should place it at `./target/release/rainbeam`

okay so what exactly do i do to get the rainbeam online under port 80 or 8080 or w.e it says?

**Comment by trisuaso** [comment]
`127.0.0.1` is likely going to be changed to `0.0.0.0` for Windows development, however for now you'd need a reverse proxy like Nginx. The port is changed using the `port` field in your `./.config/config.toml` file.

**Comment by jakesullyneytiri** [comment]
> `127.0.0.1` is likely going to be changed to `0.0.0.0` for Windows development, however for now you'd need a reverse proxy like Nginx. The port is changed using the `port` field in your `./.config/config.toml` file.
> 
> A reverse proxy is still the most recommended route, since the server doesn't allow you to configure your TLS certificates for HTTPS.

ouch, runing on linux. So there is no way i can make it listen on public port or own domain?

**Comment by trisuaso** [comment]
Just do something like this with Nginx (or something similar):

```nginx
http {
  upstream rainbeam {
    server localhost:8080;
  }
    
  server {
    listen 80 default_server;
    listen [::]:80 default_server; 
    server_name rainbeam;

    include /etc/nginx/default.d/*.conf;
    location / {
      proxy_pass http://rainbeam;
    }
  }
}
```

All you need to do is use a reverse proxy to forward the actual server's port.

**Comment by jakesullyneytiri** [comment]
> Just do something like this with Nginx (or something similar):
> 
> ```nginx
> http {
>   upstream rainbeam {
>     server localhost:8080;
>   }
>     
>   server {
>     listen 80 default_server;
>     listen [::]:80 default_server; 
>     server_name rainbeam;
> 
>     include /etc/nginx/default.d/*.conf;
>     location / {
>       proxy_pass http://rainbeam;
>     }
>   }
> }
> ```
> 
> All you need to do is use a reverse proxy to forward the actual server's port.

ty for suggestion but sadly cpnginx i use does not like using this coding, when i apply it to a domain and reboot nginx it crashes and fails to start so i have to change vhosts template back to exisiting one and reboot nginx and it works as normal again.

**Comment by trisuaso** [comment]
You may need to tweak it a little, but you only need to include the `upstream` and `server` parts. The `http` part of that example is just to show you where it goes.

You can run `sudo nginx -t` to test your config file
